Added Bootstrap writeup
o-d-i-n/DevBible pull request #15
Opened 2016-10-05 07:05 UTC by xadahiya

2016-10-05 10:52 UTC, mbad0la requested changes
Hi @xadahiya 
The content looks fine, although it is quite grammatically incorrect at places. Can you please correct it?

2016-10-05 11:15 UTC, xadahiya commented
Sure, will do

2016-10-05 11:19 UTC, xadahiya commented
@mbad0la can you point what errors are you talking about?

2016-10-05 11:26 UTC, mbad0la commented on Frameworks.md
> +Bootstrap is an open-source Javascript framework developed by the team at Twitter. It is a combination of HTML, CSS, and Javascript code designed to help build user interface components. Bootstrap wa
Bootstrap isn't a JavaScript Framework

2016-10-05 11:26 UTC, mbad0la commented on Frameworks.md
> +Also it is called Front-end-framework.
Improper sentence

2016-10-05 11:27 UTC, mbad0la commented on Frameworks.md
> +Bootstrap is a free collection of tools for creating a websites and web applications.
`a websites` is wrong

2016-10-05 11:27 UTC, mbad0la commented on Frameworks.md
> +#### Some Reasons for programmers preferred Bootstrap Framework
Improper sentence

2016-10-05 11:28 UTC, mbad0la reviewed
I guess this is fair enough to give you a rough idea.

2016-10-05 11:29 UTC, xadahiya commented
Sorry I took it from stack overflow, will fix this right away :-) .

2016-10-05 17:19 UTC, mbad0la commented
@xadahiya please rebase your branch as well. Thanks!

2016-10-15 13:16 UTC, mbad0la commented
@xadahiya please let me know the progress, else I'll be closing this PR in a day or two.

2016-11-09 18:25 UTC, closed without merging