Update Frameworks.md
o-d-i-n/DevBible pull request #21
Opened 2016-10-19 10:37 UTC by antimatter96

Currently adding Expressjs. Hope to complete it by 2016/10/20

2016-10-19 13:26 UTC, antimatter96 commented
#10

2016-10-21 02:25 UTC, mbad0la requested changes

2016-10-21 02:25 UTC, mbad0la commented on Frameworks.md
> +Django also includes more advance features such as an administrative interface, user authentication and a caching
Why is there content on Django for the ExpressJS section?

2016-10-21 15:10 UTC, antimatter96 commented on Frameworks.md
> +Django also includes more advance features such as an administrative interface, user authentication and a caching
Was using as template.

2016-10-23 06:32 UTC, mbad0la commented on Frameworks.md
> +Django also includes more advance features such as an administrative interface, user authentication and a caching
By when will this PR be ready?

2016-10-25 18:16 UTC, antimatter96 commented
Was using as template. Need changes

2016-10-28 17:06 UTC, antimatter96 commented
@mbad0la done

2016-10-28 17:17 UTC, mbad0la commented
Will check it out as soon as possible!

Mayank Badola
University of Delhi - '17
B.E. Computer Engineering
Netaji Subhas Institute of Technology
On 28 Oct 2016 10:37 p.m., "Arpit Jain" <notifications@github.com> wrote:

> @mbad0la <https://github.com/mbad0la> done
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/o-d-i-n/DevBible/pull/21#issuecomment-256974783>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AIHAIz3CulXfvxG3QiF_sR-2d_82FmZLks5q4iuQgaJpZM4Ka0Jq>
> .
>

2016-11-09 18:24 UTC, mbad0la approved these changes

2016-11-09 18:25 UTC, merged